logging:
  config: classpath:logback-spring.groovy
server:
  port: 8081
  compression:
    enabled: true
spring:
  jackson:
    default-property-inclusion: non_empty
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false