version: "3"
services:
  portainer:
    image: portainer/portainer
    environment:
      TZ: "Asia/Shangsha"
    ports:
      - "9090:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
